name: Build Hugo & Deploy gh-pages
on:
  push:
    branches: [ main ]
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Hugo Extended
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Compile static site
        run: hugo --gc --minify
      - name: Push static files to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # 补充权限相关配置
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com

 
